import { ItemView, Modal, Notice, Setting, TFile, WorkspaceLeaf, setIcon } from "obsidian";
import type TableTools from "./main";
import { describeRoll, roll, signed } from "./dice";
import { armorClass, creatureFiles, dexterityModifier, playerFiles, readStatblock } from "./statblock";
import { Combat, EncounterSet, Participant, ParticipantKind } from "./types";

export const COMBAT_VIEW = "tt-combat";
export const newCombat = (): Combat => ({ name: "Combat", active: false, round: 0, turn: 0, participants: [], log: [] });
export const combatContext = (combat: Combat): string => `## Combat\nRound: ${combat.round}\n${combat.participants.map(participant => `${participant.name}: ${participant.hp}/${participant.hpMax}`).join("\n")}`;
const conditionEntries = (strings: import("./strings").Strings): Array<[string, string]> => [[strings.conditionBlinded, strings.conditionBlinded], [strings.conditionCharmed, strings.conditionCharmed], [strings.conditionDeafened, strings.conditionDeafened], [strings.conditionFrightened, strings.conditionFrightened], [strings.conditionGrappled, strings.conditionGrappled], [strings.conditionIncapacitated, strings.conditionIncapacitated], [strings.conditionInvisible, strings.conditionInvisible], [strings.conditionParalyzed, strings.conditionParalyzed], [strings.conditionPetrified, strings.conditionPetrified], [strings.conditionPoisoned, strings.conditionPoisoned], [strings.conditionProne, strings.conditionProne], [strings.conditionRestrained, strings.conditionRestrained], [strings.conditionStunned, strings.conditionStunned], [strings.conditionUnconscious, strings.conditionUnconscious], [strings.conditionConcentration, strings.conditionConcentration], [strings.conditionExhaustion, strings.conditionExhaustion], [strings.conditionDying, strings.conditionDying]];

export class CombatView extends ItemView {
  constructor(leaf: WorkspaceLeaf, readonly plugin: TableTools) { super(leaf); }
  getViewType(): string { return COMBAT_VIEW; }
  getDisplayText(): string { return this.plugin.strings.combat; }
  getIcon(): string { return "swords"; }
  async onOpen(): Promise<void> { this.render(); }
  render(): void {
    const root = this.contentEl; root.empty(); root.addClass("tt-combat");
    const controls = root.createDiv("tt-combat-controls");
    const button = (label: string, callback: () => void): void => { const item = controls.createEl("button", { text: label }); item.onclick = callback; };
    button(this.plugin.strings.players, () => new PlayerPicker(this.app, this).open());
    button(this.plugin.strings.enemies, () => new CreaturePicker(this.app, this).open());
    button(this.plugin.strings.rollInitiative, () => this.rollInitiative());
    button(this.plugin.combat.active ? this.plugin.strings.nextTurn : this.plugin.strings.start, () => this.plugin.combat.active ? this.advance(1) : this.start());
    button(this.plugin.strings.clearCombat, () => { this.plugin.combat = newCombat(); void this.persist(); });
    root.createEl("h3", { text: `${this.plugin.strings.round}: ${this.plugin.combat.round || "-"}` });
    if (!this.plugin.combat.participants.length) root.createEl("p", { text: this.plugin.strings.emptyCombat });
    const table = root.createEl("table", { cls: "tt-table" }); const row = table.createEl("tr"); for (const label of ["", "Initiative", "Name", "AC", "HP", ""]) row.createEl("th", { text: label });
    for (const participant of this.sorted()) { const item = table.createEl("tr", { cls: participant.hp <= 0 ? "tt-defeated" : "" }); item.createEl("td", { text: participant.initiative === null ? "-" : String(participant.initiative) }); item.createEl("td", { text: participant.name }); item.createEl("td", { text: String(participant.ac) }); item.createEl("td", { text: `${participant.hp}/${participant.hpMax}${participant.temporaryHp ? ` +${participant.temporaryHp}` : ""}` }); item.createEl("td", { text: participant.conditions.join(", ") }); item.createEl("td", { text: participant.note }); const actions = item.createEl("td"); const input = actions.createEl("input", { attr: { placeholder: this.plugin.strings.damage } }); input.onkeydown = event => { if (event.key === "Enter") this.applyRowInput(participant, input.value); }; const hit = actions.createEl("button", { text: this.plugin.strings.damage }); hit.onclick = () => new AmountModal(this.app, this.plugin.strings, amount => this.applyAmount(participant, amount)).open(); const heal = actions.createEl("button", { text: this.plugin.strings.healing }); heal.onclick = () => new AmountModal(this.app, this.plugin.strings, amount => this.applyAmount(participant, -amount)).open(); const conditions = actions.createEl("button", { text: this.plugin.strings.conditions }); conditions.onclick = () => new ConditionsModal(this.app, this.plugin.strings, participant, () => void this.persist()).open(); const hidden = actions.createEl("button", { text: this.plugin.strings.edit }); hidden.onclick = () => this.setHidden(participant, !participant.hidden); const remove = actions.createEl("button", { text: this.plugin.strings.remove }); remove.onclick = () => { this.plugin.combat.participants = this.plugin.combat.participants.filter(current => current.id !== participant.id); void this.persist(); }; }
    const log = root.createDiv("tt-combat-log"); log.createEl("h4", { text: "Log" }); for (const entry of this.plugin.combat.log.slice(-40).reverse()) log.createEl("div", { text: entry });
  }
  sorted(): Participant[] { return [...this.plugin.combat.participants].sort((left, right) => (right.initiative ?? -Infinity) - (left.initiative ?? -Infinity)); }
  async addCreature(file: TFile, quantity = 1): Promise<void> { const statblock = await readStatblock(this.app, file); for (let index = 0; index < quantity; index += 1) this.plugin.combat.participants.push({ id: crypto.randomUUID(), name: quantity > 1 ? `${file.basename} ${index + 1}` : file.basename, kind: "enemy", initiative: null, modifier: dexterityModifier(statblock ?? undefined), ac: armorClass(statblock ?? undefined), hpMax: statblock?.hp ?? 10, hp: statblock?.hp ?? 10, temporaryHp: 0, conditions: [], note: "", hidden: false, source: file.path, statblock: statblock ?? undefined, cr: statblock?.cr === undefined ? undefined : String(statblock.cr) }); await this.persist(); }
  addPlayer(file: TFile): void { const fields = this.app.metadataCache.getFileCache(file)?.frontmatter ?? {}; this.plugin.combat.participants.push({ id: crypto.randomUUID(), name: file.basename, kind: "player", initiative: null, modifier: Number(fields.init_mod ?? 0), ac: Number(fields.ac ?? 10), hpMax: Number(fields.hp ?? 10), hp: Number(fields.hp ?? 10), temporaryHp: 0, conditions: [], note: "", hidden: false, source: file.path, level: Number(fields.level ?? 1) }); void this.persist(); }
  rollInitiative(): void { for (const participant of this.plugin.combat.participants) participant.initiative ??= roll(`1d20${signed(participant.modifier)}`).total; void this.persist(); }
  start(): void { this.rollInitiative(); this.plugin.combat.active = true; this.plugin.combat.round = 1; this.plugin.combat.turn = 0; void this.persist(); }
  advance(direction: number): void { const count = this.sorted().length; if (!count) return; this.plugin.combat.turn = (this.plugin.combat.turn + direction + count) % count; if (direction > 0 && this.plugin.combat.turn === 0) this.plugin.combat.round += 1; void this.persist(); }
  applyRowInput(participant: Participant, value: string): void { const input = value.trim().toLowerCase(); if (/^t\d+$/.test(input)) { participant.temporaryHp = Math.max(participant.temporaryHp, Number(input.slice(1))); this.plugin.combat.log.push(`${participant.name}: ${this.plugin.strings.temporaryHitPoints} ${participant.temporaryHp}`); void this.persist(); return; } if (/^\+\d+$/.test(input)) { this.applyAmount(participant, -Number(input.slice(1))); return; } if (/^\d+$/.test(input)) { this.applyAmount(participant, Number(input)); return; } new Notice(this.plugin.strings.invalidStatblock); }
  applyAmount(participant: Participant, amount: number): void { if (amount >= 0) { const absorbed = Math.min(participant.temporaryHp, amount); participant.temporaryHp -= absorbed; participant.hp = Math.max(0, participant.hp - amount + absorbed); if (participant.hp === 0 && participant.kind === "player" && !participant.conditions.includes(this.plugin.strings.conditionDying)) participant.conditions.push(this.plugin.strings.conditionDying); } else { participant.hp = Math.min(participant.hpMax, participant.hp - amount); if (participant.hp > 0) participant.conditions = participant.conditions.filter(condition => condition !== this.plugin.strings.conditionDying); } this.plugin.combat.log.push(`${participant.name}: ${amount >= 0 ? this.plugin.strings.damage : this.plugin.strings.healing} ${Math.abs(amount)}`); void this.persist(); }
  setHidden(participant: Participant, hidden: boolean): void { participant.hidden = hidden; this.plugin.combat.log.push(`${participant.name}: ${hidden ? "hidden" : "visible"}`); void this.persist(); }
  setNote(participant: Participant, note: string): void { participant.note = note; this.plugin.combat.log.push(`${participant.name}: ${this.plugin.strings.edit}`); void this.persist(); }
  private async persist(): Promise<void> { await this.plugin.save(); this.render(); }
}

class CreaturePicker extends Modal { constructor(app: import("obsidian").App, readonly view: CombatView) { super(app); } onOpen(): void { for (const file of creatureFiles(this.app, this.view.plugin.bestiaryPaths())) new Setting(this.contentEl).setName(file.basename).addButton(button => button.setButtonText(this.view.plugin.strings.add).onClick(() => void this.view.addCreature(file))); } }
class PlayerPicker extends Modal { constructor(app: import("obsidian").App, readonly view: CombatView) { super(app); } onOpen(): void { for (const file of playerFiles(this.app, this.view.plugin.partyPath())) new Setting(this.contentEl).setName(file.basename).addButton(button => button.setButtonText(this.view.plugin.strings.add).onClick(() => this.view.addPlayer(file))); } }
class AmountModal extends Modal { constructor(app: import("obsidian").App, readonly strings: import("./strings").Strings, readonly apply: (amount: number) => void) { super(app); } onOpen(): void { let amount = 0; new Setting(this.contentEl).setName(this.strings.damage).addText(input => input.inputEl.type = "number").addButton(button => button.setButtonText(this.strings.save).setCta().onClick(() => { if (Number.isFinite(amount) && amount > 0) this.apply(amount); this.close(); })); const input = this.contentEl.querySelector("input"); if (input instanceof HTMLInputElement) input.onchange = () => { amount = Number(input.value); }; } onClose(): void { this.contentEl.empty(); } }
class ConditionsModal extends Modal { constructor(app: import("obsidian").App, readonly strings: import("./strings").Strings, readonly participant: Participant, readonly persist: () => void) { super(app); } onOpen(): void { this.contentEl.createEl("h3", { text: this.strings.conditions }); for (const [name, value] of conditionEntries(this.strings)) { const button = this.contentEl.createEl("button", { text: name }); button.onclick = () => { this.participant.conditions = this.participant.conditions.includes(value) ? this.participant.conditions.filter(condition => condition !== value) : [...this.participant.conditions, value]; this.persist(); }; } } onClose(): void { this.contentEl.empty(); } }
