/**
 * Every user-facing text in Table Tools. Values may contain {placeholders}.
 * A vault can override any key through _local/plugins/table-tools/strings.json.
 */
export const englishStrings = {
  // Plugin
  ribbonCombat: "Table Tools: Combat",
  ribbonAssistant: "Table Tools: Assistant",
  commandOpenCombat: "Open combat",
  commandOpenAssistant: "Open assistant",
  commandNextTurn: "Combat: next turn",
  commandPreviousTurn: "Combat: previous turn",
  commandRollInitiative: "Combat: roll initiative",
  commandClearCombat: "Combat: clear",
  commandAskSelection: "Assistant: ask about the selected text",
  selectTextFirst: "Select some text first.",
  stringsOverrideInvalid: "Table Tools could not read _local/plugins/table-tools/strings.json; the English strings are in use.",

  // Settings
  settingsAssistantHeading: "Assistant (Google Gemini)",
  settingsApiKey: "API key",
  settingsApiKeyDescription: "From Google AI Studio (aistudio.google.com, Get API key). Stored locally in this plugin's data.json; do not commit it to Git.",
  settingsModel: "Model",
  settingsModelDescription: "Click \u201cFetch list\u201d to see which models your key can use.",
  settingsFetchModels: "Fetch list",
  settingsNeedApiKey: "Enter an API key first.",
  settingsModelCount: "Models: {count}",
  settingsModelListEmpty: "The list is empty.",
  settingsTemperature: "Temperature",
  settingsTemperatureDescription: "0 is predictable, 1 is creative.",
  settingsSystemPrompt: "System prompt",
  settingsSystemPromptDescription: "Who the assistant is and how it should answer.",
  settingsContextLimit: "Context limit (characters)",
  settingsContextLimitDescription: "How much note text to include with a question.",
  settingsContextBudget: "Retrieval budget (tokens)",
  settingsContextBudgetDescription: "Maximum total size for pinned and retrieved context.",
  settingsToolSteps: "Maximum tool steps",
  settingsToolStepsDescription: "Maximum read-only tool rounds for one answer.",
  settingsActivePointer: "Active run pointer",
  settingsCampaignOverride: "Campaign note override",
  settingsWorldDayOverride: "World-day note override",
  settingsUseCurrentRun: "Leave empty to use the current run.",
  settingsCombatHeading: "Combat",
  settingsBestiaryOverride: "Bestiary folder override",
  settingsBestiaryOverrideDescription: "Leave empty to use the shared and campaign homebrew bestiaries.",
  settingsPartyOverride: "Party folder override",
  settingsAverageHitPoints: "Average enemy hit points",
  settingsAverageHitPointsDescription: "Turn off to roll hit points from hit_dice.",
  settingsGroupInitiative: "Shared initiative for groups",
  settingsGroupInitiativeDescription: "Several identical creatures act together.",
  settingsAttackBonusPhrases: "Attack bonus phrases",
  settingsAttackBonusPhrasesDescription: "Comma-separated phrases that follow an attack bonus in statblocks, so the bonus can be clicked to roll.",

  // Combat view
  combatTitle: "Combat",
  defaultCombatName: "Encounter",
  toolbarPlayers: "Players",
  toolbarEnemy: "Enemy",
  toolbarInitiative: "Initiative",
  toolbarStart: "Start",
  toolbarPrevious: "Previous",
  toolbarNext: "Next",
  roundLabel: "Round",
  encounterSetsTitle: "Encounter sets",
  exportToNote: "Save to the active note",
  newCombat: "New combat (clear)",
  confirmClear: "Clear the combat?",
  confirmClearAction: "Clear",
  cancel: "Cancel",
  difficultyTrivial: "trivial",
  difficultyEasy: "easy",
  difficultyMedium: "medium",
  difficultyHard: "hard",
  difficultyDeadly: "deadly",
  difficultyDetail: "\u00b7 {xp} XP (adjusted {adjusted}) \u00b7 thresholds for {players} players: {thresholds}",
  emptyCombat: "The combat is empty.",
  emptyCombatHint: "Add players from the party and enemies from the bestiary, then Start. Initiative is rolled automatically for everyone who has none.",
  columnInitiative: "Init",
  columnName: "Name",
  columnAc: "AC",
  columnHp: "HP",
  columnDamage: "Damage / +heal",
  columnConditions: "Conditions",
  modifierTitle: "Modifier {modifier}",
  chipCr: "CR {cr}",
  chipLevel: "Level {level}",
  damagePlaceholder: "12 or +5",
  damageTitle: "Enter: damage \u00b7 +5: heal \u00b7 t5: temporary hit points \u00b7 Shift+Enter: heal",
  invalidAmount: "Enter a damage amount, +N to heal, or tN for temporary hit points.",
  conditionChipTitle: "{description} \u00b7 click to remove",
  addCondition: "Add condition",
  editParticipant: "Note, name, AC",
  hiddenFromPlayers: "Hidden from the players",
  visibleToPlayers: "Visible to the players",
  removeParticipant: "Remove",
  noStatblock: "This note has no statblock.",
  manualParticipant: "Entered manually, without a statblock.",
  openNote: "Open note",
  selectRowHint: "Click a row to see its card.",
  logTitle: "Log",

  // Combat log and notices
  logAdded: "Added: {name} \u00d7{quantity}",
  logInitiative: "Initiative rolled.",
  logRound: "\u2014 Round {round} \u2014",
  logDamage: "{name} takes {amount} damage \u2192 {hp}/{max}",
  logFalls: "{name} falls.",
  logHealing: "{name} regains {amount} HP \u2192 {hp}/{max}",
  logTemporary: "{name}: temporary HP {amount}",
  logRemoved: "Removed {name}.",
  logRoll: "{name}: {roll}",
  rollCritical: "\u2605 critical!",
  rollNaturalOne: "\u2717 natural 1",
  playerAlreadyInCombat: "{name} is already in the combat.",
  initiativeRolledFor: "Rolled initiative for: {names}",
  invalidStatblock: "Invalid statblock YAML in {path}.",
  noteMissing: "Note not found: {path}",

  // Statblock card
  cardNoteLink: "note",
  cardAc: "AC",
  cardHp: "HP",
  cardSpeed: "Speed",
  abilityStrength: "STR",
  abilityDexterity: "DEX",
  abilityConstitution: "CON",
  abilityIntelligence: "INT",
  abilityWisdom: "WIS",
  abilityCharisma: "CHA",
  rollAbilityTitle: "Roll d20 + modifier",
  clickToRoll: "Click to roll",
  lineSaves: "Saving throws",
  lineSkills: "Skills",
  lineVulnerabilities: "Damage vulnerabilities",
  lineResistances: "Damage resistances",
  lineImmunities: "Damage immunities",
  lineConditionImmunities: "Condition immunities",
  lineSenses: "Senses",
  lineLanguages: "Languages",
  lineChallenge: "Challenge",
  challengeValue: "{cr} ({xp} XP)",
  sectionTraits: "Traits",
  sectionActions: "Actions",
  sectionBonusActions: "Bonus actions",
  sectionReactions: "Reactions",
  sectionLegendaryActions: "Legendary actions",
  sectionLairActions: "Lair actions",
  sectionHomebrew: "GM notes (homebrew)",

  // Combat modals
  searchBestiary: "Search the bestiary\u2026",
  creatureOption: "{name} (CR {cr})",
  quantity: "How many?",
  sharedInitiativeForGroup: "Shared initiative for the group",
  add: "Add",
  addPlayersTitle: "Add players",
  fromPartyNotes: "From the party notes (hp, ac, init_mod, and level frontmatter fields; fill in anything missing in the table):",
  playerSummary: "AC {ac} \u00b7 HP {hp} \u00b7 init {modifier} \u00b7 level {level}",
  fromInitiativeTracker: "From Initiative Tracker:",
  manualEntry: "Manually:",
  nameLabel: "Name",
  descriptionLabel: "Description",
  playerNumbers: "AC / HP / initiative modifier / level",
  addSelected: "Add selected",
  conditionsTitle: "Conditions: {name}",
  done: "Done",
  editTitle: "Edit",
  editMaximumHp: "Maximum HP",
  editInitiativeModifier: "Initiative modifier",
  editLevel: "Level",
  editKind: "Kind",
  kindPlayer: "player",
  kindEnemy: "enemy",
  kindAlly: "ally",
  editNote: "Note",
  editNoteHint: "For example: \u201chas the key\u201d, \u201cflees at 10 HP\u201d.",
  save: "Save",
  encounterSetsHint: "An encounter set is a list of enemies prepared before the session. Loading it adds them to the current combat.",
  noEncounterSets: "No encounter sets yet.",
  memberSummary: "{name} \u00d7{quantity}",
  load: "Load",
  deleteEncounterSet: "Delete set",
  saveCurrentEnemies: "Save the current enemies as a set",
  saveEncounterSet: "Save set",
  defaultSetName: "Encounter set",
  encounterSetSaved: "Encounter set saved.",

  // Export
  exportHeading: "Combat: {name} (round {round})",
  exportDifficulty: " \u00b7 {level}, {xp} XP",
  exportColumns: "| Init | Who | AC | HP | Conditions |",
  exportSaved: "Saved the combat to {note}.",
  exportCopied: "No open note; the combat was copied to the clipboard.",

  // Conditions
  conditionBlinded: "Blinded",
  conditionBlindedDescription: "Cannot see. Attacks against it have advantage; its attacks have disadvantage.",
  conditionCharmed: "Charmed",
  conditionCharmedDescription: "Cannot attack the charmer; the charmer has advantage on social checks against it.",
  conditionDeafened: "Deafened",
  conditionDeafenedDescription: "Cannot hear.",
  conditionFrightened: "Frightened",
  conditionFrightenedDescription: "Disadvantage on checks and attacks while the source is in sight; cannot move closer to it.",
  conditionGrappled: "Grappled",
  conditionGrappledDescription: "Speed 0.",
  conditionIncapacitated: "Incapacitated",
  conditionIncapacitatedDescription: "No actions or reactions.",
  conditionInvisible: "Invisible",
  conditionInvisibleDescription: "Attacks against it have disadvantage; its attacks have advantage.",
  conditionParalyzed: "Paralyzed",
  conditionParalyzedDescription: "Incapacitated and cannot move. Fails Strength and Dexterity saves. Attacks against it have advantage; hits from within 5 feet are critical.",
  conditionPetrified: "Petrified",
  conditionPetrifiedDescription: "Turned to stone. Resistance to all damage.",
  conditionPoisoned: "Poisoned",
  conditionPoisonedDescription: "Disadvantage on attack rolls and ability checks.",
  conditionProne: "Prone",
  conditionProneDescription: "Can only crawl. Attacks from within 5 feet have advantage against it; from farther away, disadvantage.",
  conditionRestrained: "Restrained",
  conditionRestrainedDescription: "Speed 0. Attacks against it have advantage; its attacks have disadvantage. Disadvantage on Dexterity saves.",
  conditionStunned: "Stunned",
  conditionStunnedDescription: "Incapacitated. Fails Strength and Dexterity saves. Attacks against it have advantage.",
  conditionUnconscious: "Unconscious",
  conditionUnconsciousDescription: "Incapacitated and prone. Fails Strength and Dexterity saves. Attacks against it have advantage; hits from within 5 feet are critical.",
  conditionConcentration: "Concentration",
  conditionConcentrationDescription: "Maintaining a spell. After taking damage, Constitution save against DC 10 or half the damage, whichever is higher.",
  conditionExhaustion: "Exhaustion",
  conditionExhaustionDescription: "A level of exhaustion; record the level in the note.",
  conditionDying: "Dying",
  conditionDyingDescription: "0 HP. Death saving throws.",

  // Assistant view
  assistantTitle: "Table Tools assistant",
  modelChipTitle: "Model; change it in the settings",
  contextRun: "Run",
  contextRunTitle: "Include the campaign, run, and state of the active run",
  contextWorldDay: "Today",
  contextWorldDayTitle: "Include the world date, moon, and season",
  contextNote: "Note",
  contextNoteTitle: "Include the active note",
  contextCombat: "Combat",
  contextCombatTitle: "Include the combat state",
  contextRetrieval: "Search",
  contextRetrievalTitle: "Retrieve relevant notes from the active scope",
  commandRebuildAssistantIndex: "Assistant: rebuild index",
  assistantToolLimit: "Tool step limit reached.",
  assistantToolTrace: "Tools used",
  assistantSources: "Sources",
  assistantRetrievalInstructions: "Use supplied wikilink citations when you rely on retrieved context. Say when the context lacks the answer or use a tool. Never reveal secret notes in read-aloud text.",
  assistantIndexing: "Indexing {count}...",
  assistantIndexed: "Indexed {notes} notes and {chunks} chunks.",
  assistantScopePolicyInvalid: "Assistant scope policy is invalid; the shipped policy is in use.",
  attachNoteTitle: "Attach a specific note to the context",
  attachNotePlaceholder: "Attach a note to the context\u2026",
  newConversation: "New conversation",
  removeAttachment: "Remove from the context",
  assistantReady: "The co-GM is ready. Ask a question or use a shortcut below.",
  assistantNeedsKey: "Paste a Google AI key into the Table Tools settings to begin.",
  assistantContextHint: "Context (campaign, date, active note, combat) is attached automatically; use the toggles at the top.",
  inputPlaceholder: "Ask\u2026 (Enter sends, Shift+Enter adds a line)",
  send: "Send",
  writing: "Writing\u2026",
  stop: "stop",
  stopped: "(stopped)",
  copy: "Copy",
  copied: "Copied.",
  insertIntoNote: "Insert into the active note (at the cursor)",
  openNoteInEditor: "Open a note in the editor.",
  inserted: "Inserted.",
  regenerate: "Regenerate",
  noApiKey: "No API key; see the Table Tools settings.",
  quickSceneLabel: "Describe the scene",
  quickScenePrompt: "Describe the scene the party is in right now (based on the active note) with three senses, at most four sentences, ready to read aloud.",
  quickNpcLabel: "What does the NPC do?",
  quickNpcPrompt: "Take the NPC from the active note. Give three things they could do right now, following what they want and what they fear. One sentence each.",
  quickPasserbyLabel: "Passer-by",
  quickPasserbyPrompt: "Invent a random character the party has just approached in the place from the active note: a name that fits the place, one detail of appearance, one mannerism, what they want, and one secret. Mark it as (suggestion).",
  quickConsequencesLabel: "Consequences",
  quickConsequencesPrompt: "The party has just done what I describe below. Give three consequences: immediate, within this session, and in the background (factions). Keep it short.\n\n",
  quickSummaryLabel: "Summarise",
  quickSummaryPrompt: "Based on the active note, write a session summary to read aloud to the players: three to five sentences, then a second paragraph of open threads as bullet points.",
  quickNamesLabel: "Names",
  quickNamesPrompt: "Give eight names that fit the context of the active note (culture, region). Names only, no descriptions.",
  quickMechanicsLabel: "Mechanics",
  quickMechanicsPrompt: "A player wants to do what I describe below. Suggest a check (ability, skill, DC) and what happens on a success, a failure, and a failure by 5 or more.\n\n",

  // Gemini errors
  errorInvalidKey: "Invalid API key. Check the Table Tools settings.",
  errorForbidden: "Access denied (403). The key has no permission for this model, or the API is not enabled.",
  errorModelMissing: "The model does not exist (404). Fetch the model list in the settings. {message}",
  errorRateLimit: "Rate limit reached (429). Wait a moment or switch to a lighter model.",
  errorGeneric: "Error {status}: {message}",
  errorUnknown: "unknown",
  responseBlocked: "(Response blocked by Google's filter: {reason})",
};

export type StringKey = keyof typeof englishStrings;
export type Strings = Record<StringKey, string>;

/** Merges a local override over the English strings; unknown keys and non-string values are ignored. */
export function createStrings(override: unknown): Strings {
  const result: Strings = { ...englishStrings };
  if (!override || typeof override !== "object" || Array.isArray(override)) return result;
  for (const key of Object.keys(englishStrings) as StringKey[]) {
    const value = (override as Record<string, unknown>)[key];
    if (typeof value === "string") result[key] = value;
  }
  return result;
}

/** Replaces {placeholders} with values; unknown placeholders are left as they are. */
export function format(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => key in values ? String(values[key]) : match);
}

const capitalised = (key: string): string => key.charAt(0).toUpperCase() + key.slice(1);

export function conditionLabel(strings: Strings, condition: string): string {
  return strings[`condition${capitalised(condition)}` as StringKey] ?? condition;
}

export function conditionDescription(strings: Strings, condition: string): string {
  return strings[`condition${capitalised(condition)}Description` as StringKey] ?? "";
}
